### PR TITLE
games-strategy/openra-20171014: deny FEATURES=network-sandbox because of fetching deps

### PR DESCRIPTION
**Pull request by soredake**

### CODE REVIEW

**Comment by cerebrum** [comment]
@soredake, I've fixed manifest in 20171014-r1 already. Use -r2 for your latest change. Use the following procedure:
`cd /usr/local/portage/layman/dr/games-strategy/openra` or whatever your path is.
Sync with upstream: `git fetch --all`
`git checkout origin/master`
To work on something: `git checkout -b myfeature`
`cp openra-20171014-r1.ebuild openra-20171014-r2.ebuild`
...
`PORTDIR_OVERLAY="/usr/local/portage/layman/dr/ ${PORTDIR_OVERLAY}" repoman manifest` or whatever path you have for layman.
`git add openra-20171014-r2.ebuild Manifest`
`git commit -m 'myfeature'`
Before publishing your changes it's a good idea to rebase them up to the latest upstream version:
`git fetch --all`
`git rebase origin/master`
Now test that it still works. If so publish your changes:
`git push origin myfeature`
Use new -r2, -r3 etc. for every new myfeature. And don't forget to regen manifests.
Also, does your English spelling correct? "games-strategy/openra" - It requires or it does require "'network-sandbox' to be disabled in FEATURES".

**Comment by soredake** [comment]
I know how to do rebase and update manifest, thanks.

@cerebrum 
>Also, does your English spelling correct?

I copied this from
https://github.com/csmk/frabjous/blob/master/net-p2p/go-ipfs/go-ipfs-0.4.11.ebuild#L30-L31
Feel free to correct the spelling if it looks wrong for you.

**Comment by cerebrum** [comment]
@soredake,  Please, use "games-strategy/openra requires 'network-sandbox' to be disabled in FEATURES" variant. I have just approved it using native speaker.
Thin-manifests are disabled by default. The dr repository isn't fetched through a Git, so we need to make sure of integrity of local files too. Using git in this case would be a useless waste of space. Thank you.

**Comment by soredake** [comment]
Corrected.

**Pull request merged**
